#!/usr/bin/env zsh
set -e

workdir=$(dirname $0)
distro=$(uname)
if [[ $distro == "Darwin" ]]; then
    stow_folders=$workdir/env/mac
elif [[ $distro == "Linux" ]]; then
    stow_folders=$workdir/env/debian
fi

pushd $workdir
while read folder; do
    echo "stowing $folder"
    if [[ $folder == "home" ]]; then
        target_dir=$HOME
    else
        target_dir="$XDG_CONFIG_HOME/$folder"
    fi
    mkdir -p $target_dir && stow --target $target_dir --restow $folder 1&> /dev/null
done < $stow_folders
popd
