#!/usr/bin/env bash
set -e

workdir=$(dirname "$0")
stow_config=$workdir/env
declare -a stow_folders

while IFS= read -r line; do
	stow_folders+=("$line")
done <"$stow_config"

pushd "$workdir/modules" >/dev/null
for folder in "${stow_folders[@]}"; do
	echo "stowing $folder"
	if [[ $folder == "home" ]]; then
		target_dir=$HOME
		stow_flag="--stow"
	else
		target_dir="$XDG_CONFIG_HOME/$folder"
		stow_flag="--restow"
	fi
	mkdir -p "$target_dir" && stow --dotfiles --target "$target_dir" "$stow_flag" "$folder"
done
popd >/dev/null
