#!/usr/bin/env bash

export STOW_FOLDERS="home,nvim,tmux,zsh"
export GPG_TTY=$(tty)

genFileAliases() {
  file="$DOTFILES/$3"
  declare -A label
  label[dotfile]="d"
  alias "e$label[$1]$2"="$vim $file"
  alias "c$label[$1]$2"="cat $file"
}

vim="nvim"
alias vim="$vim"
alias dotFileInstall="$DOTFILES/install"
alias dp="dotFileInstall && source $XDG_CONFIG_HOME/zsh/.zshrc"

genFileAliases "dotfile" "b" "$XDG_CONFIG_HOME/zsh/.zshrc"
genFileAliases "dotfile" "t" "$XDG_CONFIG_HOME/tmux/.tmux.conf"
genFileAliases "dotfile" "nv" "$XDG_CONFIG_HOME/nvim/.config/nvim/init.lua"
genFileAliases "dotfile" "nvk" "$XDG_CONFIG_HOME/nvim/.config/nvim/lua/keithhand/keymappings.lua"
