#!/usr/bin/env bash

export STOW_FOLDERS="home,nvim,tmux,zsh"
export GPG_TTY=$(tty)

_genFileAliases() {
  declare -A label
  label[dotfile]="d"
  alias "e$label[$1]$2"="$vim $3"
  alias "c$label[$1]$2"="cat $3"
}

vim="nvim"
alias vim="$vim"
alias dotFileInstall="$DOTFILES/install"
alias rz="source $XDG_CONFIG_HOME/zsh/.zshrc"
alias dp="dotFileInstall && rz"

_genFileAliases "dotfile" "a" "$XDG_CONFIG_HOME/zsh/aliases"
_genFileAliases "dotfile" "p" "$XDG_CONFIG_HOME/zsh/paths"
_genFileAliases "dotfile" "b" "$XDG_CONFIG_HOME/zsh/.zshrc"
_genFileAliases "dotfile" "t" "$XDG_CONFIG_HOME/tmux/.tmux.conf"
_genFileAliases "dotfile" "nv" "$XDG_CONFIG_HOME/nvim/init.lua"
_genFileAliases "dotfile" "nvk" "$XDG_CONFIG_HOME/nvim/lua/keithhand/keymappings.lua"
