#!/usr/bin/env bash

_addToPath() {
  if [[ "$PATH" != *"$1"* ]]; then
    export PATH=$PATH:$1
  fi
}

_addToPathFront() {
  if [[ "$PATH" != *"$1"* ]]; then
    export PATH=$1:$PATH
  fi
}

_addToPathFront "$HOME/bin:/usr/local/bin"
_addToPathFront "$HOME/.local/bin"
_addToPathFront "$HOME/.local/scripts"
_addToPathFront "$HOME/.kubectx"
_addToPath "/mnt/c/Windows/System32/WindowsPowerShell/v1.0"
_addToPath "/mnt/c/Users/rkeit/AppData/Local/Programs/Microsoft VS Code/bin"

# Add homebrew to path
if [[ ! -f $(which brew) ]]; then
  eval "$($BREW_PREFIX/bin/brew shellenv)"
fi
